force-app/main/default/objects/Car__c/fields/ArrivalDate__c.field-meta.xml
<CustomField>
    <fullName>ArrivalDate__c</fullName>
    <label>Arrival Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/ChasisNumber__c.field-meta.xml
<CustomField>
    <fullName>ChasisNumber__c</fullName>
    <label>Chasis Number</label>
    <length>174</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price of the Car</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State  of the Car</label>
    <length>174</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CarControler.cls
public with sharing class CarControler {

        @AuraEnabled(cacheable=true)
        public static List<Car__c> getAllCars(){
            return [SELECT Id, Name, ChasisNumber__c, State__c, Price__c FROM Car__c ORDER BY ArrivalDate__c ];
        }
    
    
        public static List<Car__c> searchCar(String key){
            string searchword = key + '%';
            return [SELECT Id, Name, ChasisNumber__c, State__c, Price__c
                   FROM Car__c
                   WHERE Name LIKE : searchword OR ChasisNumber__c LIKE:searchword
                   ORDER BY ArrivalDate__c DESC NULLS LAST
                   LIMIT 100];
            
        }
        @AuraEnabled
        public static Car__c getCar(String searchId){
            List<Car__c> results = [
                SELECT Id, Name, ChasisNumber__c, State__c, Price__c
                FROM Car__c
                WHERE Id = :searchId
                ORDER BY ArrivalDate__c DESC NULLS LAST ];
            if (results != null && results.size() > 0 ){
                return results[0]; 
            }
                return null;
        }
    
      
        @AuraEnabled
       public static String addCar(String payload){
        Car payloader = (Car) JSON.deserialize(payload, Car.class);
        Car__c newcar =  new Car__c(
            Name =  payloader.name,
            ChasisNumber__c = payloader.chasis,
            State__c = payloader.state,
            Price__c = payloader.price,
            ArrivalDate__c = payloader.arrivalDate
        );
        insert newcar;
        return String.valueOf(newcar.Id);
       }
       
    //    @AuraEnabled
    //    public static void updateCar(String payload){
    //     Car payloader = (Car) JSON.deserialize(payload, Car.class);
    //     List<Car__c> result = [ SELECT Id, Name, State__c, Price__c FROM Car__c  WHERE Id = :payloader.Id];
    //     for(Car__c car: result){
    //         car.State__c = payloader.state;
    //     }
    
    //     update result;
    //    }
    
       class Car{
           @AuraEnabled
           public String chasis; 
           @AuraEnabled
           public String name;
           @AuraEnabled
           public String state;
           @AuraEnabled
           public Integer price;
           @AuraEnabled
           public Date arrivalDate;
       }
    
     
}